mysite/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit', views.PostUpdateView.as_view(), name='post_edit'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/remove', views.PostDeleteView.as_view(), name='post_remove'),
    path('post/<int:pk>/comment', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove', views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/publish', views.post_publish, name='post_publish'),
]

mysite/mysite/urls.py
# from django.contrib import admin
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('blog.urls')),
#     path('accounts/login/', LoginView, name='login'),
#     path('accounts/logout/', LogoutView, name='logout', kwargs={'next_page': '/'}, ),
# ]

from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='blog:post_list'), name='logout'),
]

mysite/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    # super users has the ability to create, edit and delete posts
    # linking the author to an authorisation user ensures this
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    # can be left blank or empty
    published_date = models.DateTimeField(blank=True, null=True)

    # a publish button to be created and whenever thr button is clicked, it calls this function which sets the publish date
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    # returns the approved comments from the blog post. i.e. comments from the Comment class that have been approved
    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    # once a post has been created, the site returns you to the url named post_detail with the specific pk
    # i.e. {post_detail}/{pk}
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    # this connects a comment to a post i.e. each comment is aligned to a post.
    # Post can be directly referenced here instead of 'blog.Post' because they are in the same app and models.py file
    # if the Post model were in another app, you would need to use the {app name}.{Model Class}
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    # once a comment has been created, the site returns you to the url named post_list
    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

mysite/blog/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("author", "title", "text")

        # this allows you to grab a particular field widget e.g adding a red boarder to the text area box
        widgets = {
            # class name goes inside the css
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')

        widgets = {
            # class name goes inside the css
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

mysite/blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)

from .forms import PostForm, CommentForm
from .models import Post, Comment


# Create your views here.
class AboutView(TemplateView):
    template_name = 'about.html'


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        """
        Retrieve the list of published posts.

        This method runs a query on the Post model (Python version of running an SQL query).
        This grabs the Post model and filters it based on the specified conditions.
        __lte is a django functionality which stands for less than or equals to.
        Hence, this queryset fetches posts with a published_date that is less than or equal to the current time.
        The results are ordered by published_date in descending order.
        This is denoted by the "-" prefix on published date.

        Returns:
        QuerySet: A queryset of Post objects.
        """
        return Post.objects.filter(
            published_date__lte=timezone.now()).order_by('-published_date')


"""
Glossary of terms, attributes and variables

LoginRequiredMixin: s a mixin provided by Django that is used to restrict access to a view, 
ensuring that only authenticated users can access it.  If a user is not logged in and tries to access a view that uses
this mixin, they will be redirected to the login page.

form_class: specifies which form to use for handling user input. This is particularly useful when creating or 
editing model instances through forms. The form_class attribute indicates which form to use when rendering 
the view and processing form submissions.

redirect_field_name: this attribute is used to specify the name of the query parameter that will hold the URL to which
the user should be redirected after logging in. This is particularly relevant when using the LoginRequiredMixin.
That is, after login in the user is redirected to the page specified by redirect_field_name

success_url: this attribute defines where users will be redirected after successfully completing an action on the view.
This is only done after the action on the view has been completed which in this case is deleting a post.

reverse_lazy: this is used to hard code success_url with the url that dynamically generates based on some criteria.
"""


class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    # redirect users to the detail view once they've logged in
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class PostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    # only activated after the post has been deleted
    success_url = reverse_lazy('blog:post_list')
    model = Post


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    template_name = 'blog/post_draft_list.html'
    redirect_field_name = 'blog/post_draft_list.html'
    model = Post
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-created_date')


########################################################
########################################################
"""
This section makes use of Function based views FBVs

get_object_or_404(): This  used for getting an object from a database using a model’s manager.
It raises an Http404 exception if the object is not found. 
The Post object gotten is based on the primary key (pk) f the post.
This is particularly useful for ensuring the post with the pk exists before attempting to publish it.
"""


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # if the form is sending data to the server via a POST request
    if request.method == 'POST':
        # Initialises the form with submitted data (stores the data in the from variable)
        form = CommentForm(request.POST)
        if form.is_valid():
            # creates a new Comment instance but does not save it to the database yet.
            # This is useful because we want to modify the instance
            # (specifically, we want to assign it to the post) before saving it.
            comment = form.save(commit=False)
            # post is a foreign key in the CommentForm Model.
            # this assigns the post field in the comment to the post retrieved using get_object_or_404()
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)

    # if the form is not sending any data, initialise the form and render it on the html template
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', context={'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    # after deleting comment, django no longer has access the primary key of the post
    # this is why the primary key of the post is stored in a separate variable 'post_pk'
    # this makes the primary key of the post associated with the comment accessible.
    return redirect('blog:post_detail', pk=post_pk)

mysite/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container about">
        <h2>Your Blogging Hub: Create, Manage, and Share Your Posts with Ease</h2>
        <p>Welcome to our blog platform, where you can easily create and manage your entries! Our features include the
            ability to:</p>
        <ul>
            <li>Login</li>
            <li>List posts</li>
            <li>Publish and Remove posts</li>
            <li>Publish and remove comments</li>
            <li>Save and delete drafts</li>
        </ul>
    </div>
{% endblock %}

mysite/blog/templates/blog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>

    {#Bootstrap CSS#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    {#medium style editor#}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
          type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    {#Fonts#}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Russo+One&display=swap"
          rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-dark navbar-expand-lg bg-dark techfont">
    <div class="container-fluid">
        <a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:about' %}">About</a>
                </li>
                <li class="nav-item">
                    {#opens in a new tab#}
                    <a class="nav-link active" aria-current="page" href="https://github.com/tobikasaba" target="_blank">Github</a>
                </li>
                <li class="nav-item">
                    {#opens in a new tab#}
                    <a class="nav-link active" aria-current="page"
                       href="https://www.linkedin.com/in/tobi-kasaba-6212b413b/" target="_blank">LinkedIn</a>
                </li>
            </ul>

            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blog:post_new' %}">New Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'blog:post_draft_list' %}">Drafts</a>
                    </li>
                    <li class="nav-item">
                        {#Django requires POST request to prevent CSRF attacks#}
                        {#Using direct url to log out sends a GET request#}
                        {#To implement this, a logout form is created that sends a POST request#}
                        <form id="logout-form" method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="nav-link active">Log Out</button>
                        </form>
                    </li>
                    <li class="nav-item">
                        <span class="nav-link active" aria-current="page">Welcome: {{ user.username }}</span>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="blog_posts">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
{#Bootstrap JavaScript#}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</body>
</html>

mysite/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>New Comment</h1>
    <form method="post" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary" name="button">Post Comment</button>
    </form>
    {#Ensures the Medium style editor is applicable to the text#}
    <script> var editor = new MediumEditor('.editable');</script>
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <h2>Are you sure you want to delete "{{ object }}"?</h2>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1 class="posttitle loader">{{ post.title }}</h1>

    {% if post.published_date %}
        <div class="date postdate">
            {{ post.published_date }}
        </div>
    {% else %}
        <a class="btn btn-primary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
    {% endif %}
    <p class="postcontent">{{ post.text|safe|linebreaksbr }}</p>

    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">Edit</a>
        <a class="btn btn-danger" href="{% url 'blog:post_remove' pk=post.pk %}">Delete</a>
    {% else %}

    {% endif %}
    <hr>
    <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment </a>

    <div class="container">
        {% for comment in post.comments.all %}
            <br>
            {% if user.is_authenticated or comment.approved_comments %}
                {{ comment.created_date }}
                {% if not comment.approved_comment %}
                    <a class="btn btn-danger" href="{% url 'blog:comment_remove' pk=comment.pk %}">Delete</a>
                    <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">Approve</a>
                {% endif %}
                <p>{{ comment.text|safe|linebreaks }}</p>
                <p>Posted By: {{ comment.author }}</p>
                <hr>
            {% else %}
                <p>{{ comment.text|safe|linebreaks }}</p>
                <hr>
            {% endif %}
        {% empty %}
            <p>No Comments</p>
        {% endfor %}

    </div>
{% endblock %}

mysite/blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% if posts %}
        {% for post in posts %}
            <div class="post">
                <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
                <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                <p>{{ post.text|truncatechars:200|safe }}</p>
                <hr>
            </div>
        {% endfor %}
    {% else %}
        <h2>No Post has been written to Draft </h2>
        <p><a href="{% url 'blog:post_new' %}">Click to create a New Post</a></p>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>New Post</h1>
    <form action="" class="post-from" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="save btn btn-primary" type="submit">Save</button>
        <button class="save btn btn-danger" type="button" onclick="window.history.back();">Cancel</button>
        {#        <button class="save btn btn-danger"><a href="{{ request.META.HTTP_REFERER|escape }}">Cancel</a></button>#}
    </form>
    <script> var editor = new MediumEditor('.editable');</script>
{% endblock %}

mysite/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="centerstage">
        {% if post_list %}
            {% for post in post_list %}
                <div class="post">
                    <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                </div>
                <div class="date">
                    <p>Published on: {{ post.published_date|date:"D M Y" }}</p>
                </div>
                <p>{{ post.text|truncatechars:200|safe }}</p>
                <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
                <hr>
            {% endfor %}
        {% else %}
            <h2>No Post has been published</h2>
            {% if user.is_authenticated %}
                <p><a href="{% url 'blog:post_new' %}">Click to create a New Post</a></p>
                <p><a href="{% url 'blog:post_draft_list' %}">Click to Publish a Post from Drafts</a></p>
            {% else %}
                <h3>Login to publish a post</h3>
            {% endif %}
        {% endif %}

    </div>
{% endblock %}